./target/debug/rgb "test_roms/01-special.gb"
./target/debug/rgb "test_roms/03-op sp,hl.gb"
./target/debug/rgb "test_roms/04-op r,imm.gb"
./target/debug/rgb "test_roms/05-op rp.gb"
./target/debug/rgb "test_roms/06-ld r,r.gb"
./target/debug/rgb "test_roms/07-jr,jp,call,ret,rst.gb"
./target/debug/rgb "test_roms/08-misc instrs.gb"
./target/debug/rgb "test_roms/09-op r,r.gb"
./target/debug/rgb "test_roms/10-bit ops.gb"
./target/debug/rgb "test_roms/11-op a,(hl).gb"
./target/debug/rgb "test_roms/instr_timing.gb"
