./target/debug/rgb "01-special.gb"
./target/debug/rgb "03-op sp,hl.gb"
./target/debug/rgb "04-op r,imm.gb"
./target/debug/rgb "05-op rp.gb"
./target/debug/rgb "06-ld r,r.gb"
./target/debug/rgb "07-jr,jp,call,ret,rst.gb"
./target/debug/rgb "08-misc instrs.gb"
./target/debug/rgb "09-op r,r.gb"
./target/debug/rgb "10-bit ops.gb"
./target/debug/rgb "11-op a,(hl).gb"
