version: 2
jobs:
  style:
    docker:
      - image: circleci/rust:1.32.0-stretch
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: rustfmt --check src/main.rs
  build:
    docker:
      - image: circleci/rust:1.32.0-stretch
    steps:
      - checkout
      - run: cargo check
      - run: cargo build
